"""Initial parliamentary tables

Revision ID: 0001
Revises: 
Create Date: 2025-09-22 17:16:15.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asuntos_diputados',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('asunto_id', sa.Integer(), nullable=False),
    sa.Column('asunto', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('sumario', sa.String(), nullable=True),
    sa.Column('fecha', sa.String(), nullable=True),
    sa.Column('sesion', sa.String(), nullable=True),
    sa.Column('reunion', sa.String(), nullable=True),
    sa.Column('numero_reunion', sa.String(), nullable=True),
    sa.Column('tipo_asunto', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asunto_id')
    )
    op.create_index(op.f('ix_asuntos_diputados_asunto_id'), 'asuntos_diputados', ['asunto_id'], unique=False)
    op.create_index(op.f('ix_asuntos_diputados_id'), 'asuntos_diputados', ['id'], unique=False)
    
    op.create_table('bloques_diputados',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('bloque_id', sa.Integer(), nullable=False),
    sa.Column('bloque', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_inicio', sa.String(), nullable=True),
    sa.Column('fecha_fin', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bloque_id')
    )
    op.create_index(op.f('ix_bloques_diputados_bloque'), 'bloques_diputados', ['bloque'], unique=False)
    op.create_index(op.f('ix_bloques_diputados_bloque_id'), 'bloques_diputados', ['bloque_id'], unique=False)
    op.create_index(op.f('ix_bloques_diputados_id'), 'bloques_diputados', ['id'], unique=False)
    
    op.create_table('legisladores_diputados',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('diputado_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('nombre_completo', sa.String(), nullable=True),
    sa.Column('genero', sa.String(), nullable=True),
    sa.Column('fecha_nacimiento', sa.String(), nullable=True),
    sa.Column('lugar_nacimiento', sa.String(), nullable=True),
    sa.Column('partido', sa.String(), nullable=True),
    sa.Column('bloque_id', sa.Integer(), nullable=True),
    sa.Column('distrito', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('imagen', sa.String(), nullable=True),
    sa.Column('periodo_inicio', sa.String(), nullable=True),
    sa.Column('periodo_fin', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diputado_id')
    )
    op.create_index(op.f('ix_legisladores_diputados_apellido'), 'legisladores_diputados', ['apellido'], unique=False)
    op.create_index(op.f('ix_legisladores_diputados_bloque_id'), 'legisladores_diputados', ['bloque_id'], unique=False)
    op.create_index(op.f('ix_legisladores_diputados_diputado_id'), 'legisladores_diputados', ['diputado_id'], unique=False)
    op.create_index(op.f('ix_legisladores_diputados_distrito'), 'legisladores_diputados', ['distrito'], unique=False)
    op.create_index(op.f('ix_legisladores_diputados_id'), 'legisladores_diputados', ['id'], unique=False)
    op.create_index(op.f('ix_legisladores_diputados_nombre'), 'legisladores_diputados', ['nombre'], unique=False)
    op.create_index(op.f('ix_legisladores_diputados_partido'), 'legisladores_diputados', ['partido'], unique=False)
    
    op.create_table('votaciones_diputados',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('asunto_id', sa.Integer(), nullable=False),
    sa.Column('diputado_id', sa.Integer(), nullable=False),
    sa.Column('bloque_id', sa.Integer(), nullable=True),
    sa.Column('voto', sa.String(), nullable=False),
    sa.Column('fecha_votacion', sa.String(), nullable=True),
    sa.Column('sesion', sa.String(), nullable=True),
    sa.Column('reunion', sa.String(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('tipo_votacion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votaciones_diputados_asunto_id'), 'votaciones_diputados', ['asunto_id'], unique=False)
    op.create_index(op.f('ix_votaciones_diputados_bloque_id'), 'votaciones_diputados', ['bloque_id'], unique=False)
    op.create_index(op.f('ix_votaciones_diputados_diputado_id'), 'votaciones_diputados', ['diputado_id'], unique=False)
    op.create_index(op.f('ix_votaciones_diputados_id'), 'votaciones_diputados', ['id'], unique=False)
    op.create_index(op.f('ix_votaciones_diputados_voto'), 'votaciones_diputados', ['voto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votaciones_diputados_voto'), table_name='votaciones_diputados')
    op.drop_index(op.f('ix_votaciones_diputados_id'), table_name='votaciones_diputados')
    op.drop_index(op.f('ix_votaciones_diputados_diputado_id'), table_name='votaciones_diputados')
    op.drop_index(op.f('ix_votaciones_diputados_bloque_id'), table_name='votaciones_diputados')
    op.drop_index(op.f('ix_votaciones_diputados_asunto_id'), table_name='votaciones_diputados')
    op.drop_table('votaciones_diputados')
    
    op.drop_index(op.f('ix_legisladores_diputados_partido'), table_name='legisladores_diputados')
    op.drop_index(op.f('ix_legisladores_diputados_nombre'), table_name='legisladores_diputados')
    op.drop_index(op.f('ix_legisladores_diputados_id'), table_name='legisladores_diputados')
    op.drop_index(op.f('ix_legisladores_diputados_distrito'), table_name='legisladores_diputados')
    op.drop_index(op.f('ix_legisladores_diputados_diputado_id'), table_name='legisladores_diputados')
    op.drop_index(op.f('ix_legisladores_diputados_bloque_id'), table_name='legisladores_diputados')
    op.drop_index(op.f('ix_legisladores_diputados_apellido'), table_name='legisladores_diputados')
    op.drop_table('legisladores_diputados')
    
    op.drop_index(op.f('ix_bloques_diputados_id'), table_name='bloques_diputados')
    op.drop_index(op.f('ix_bloques_diputados_bloque_id'), table_name='bloques_diputados')
    op.drop_index(op.f('ix_bloques_diputados_bloque'), table_name='bloques_diputados')
    op.drop_table('bloques_diputados')
    
    op.drop_index(op.f('ix_asuntos_diputados_id'), table_name='asuntos_diputados')
    op.drop_index(op.f('ix_asuntos_diputados_asunto_id'), table_name='asuntos_diputados')
    op.drop_table('asuntos_diputados')
    # ### end Alembic commands ###
