"""initial parliamentary tables

Revision ID: a3160bcf44b6
Revises:
Create Date: 2025-09-24 23:28:35.502572

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a3160bcf44b6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asuntos_diputados",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("asunto_id", sa.Integer(), nullable=False),
        sa.Column("sesion", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("asunto", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("titulo", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fecha", sa.DateTime(), nullable=False),
        sa.Column("año", sa.Integer(), nullable=False),
        sa.Column("hora", sa.Time(), nullable=True),
        sa.Column("base", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mayoria", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("resultado", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("presidente", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("presentes", sa.Integer(), nullable=False),
        sa.Column("ausentes", sa.Integer(), nullable=False),
        sa.Column("abstenciones", sa.Integer(), nullable=False),
        sa.Column("afirmativos", sa.Integer(), nullable=False),
        sa.Column("negativos", sa.Integer(), nullable=False),
        sa.Column("voto_presidente", sa.Float(), nullable=True),
        sa.Column("auditoria", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_asuntos_diputados_asunto_id"),
        "asuntos_diputados",
        ["asunto_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_asuntos_diputados_id"), "asuntos_diputados", ["id"], unique=False
    )
    op.create_table(
        "asuntos_senadores",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("asunto_id", sa.Integer(), nullable=False),
        sa.Column("sesion", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("asunto", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("titulo", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fecha", sa.DateTime(), nullable=False),
        sa.Column("año", sa.Integer(), nullable=False),
        sa.Column("hora", sa.Time(), nullable=True),
        sa.Column("base", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mayoria", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("resultado", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("presidente", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("presentes", sa.Integer(), nullable=False),
        sa.Column("ausentes", sa.Integer(), nullable=False),
        sa.Column("abstenciones", sa.Integer(), nullable=False),
        sa.Column("afirmativos", sa.Integer(), nullable=False),
        sa.Column("negativos", sa.Integer(), nullable=False),
        sa.Column("voto_presidente", sa.Float(), nullable=True),
        sa.Column("auditoria", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_asuntos_senadores_asunto_id"),
        "asuntos_senadores",
        ["asunto_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_asuntos_senadores_id"), "asuntos_senadores", ["id"], unique=False
    )
    op.create_table(
        "bloques_diputados",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("bloque_id", sa.Integer(), nullable=False),
        sa.Column("bloque", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bloques_diputados_bloque_id"),
        "bloques_diputados",
        ["bloque_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_bloques_diputados_id"), "bloques_diputados", ["id"], unique=False
    )
    op.create_table(
        "bloques_senadores",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("bloque_id", sa.Integer(), nullable=False),
        sa.Column("bloque", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bloques_senadores_bloque_id"),
        "bloques_senadores",
        ["bloque_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_bloques_senadores_id"), "bloques_senadores", ["id"], unique=False
    )
    op.create_table(
        "legisladores_diputados",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("distrito", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sexo", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("imagen", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("diputado_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_legisladores_diputados_diputado_id"),
        "legisladores_diputados",
        ["diputado_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_legisladores_diputados_distrito"),
        "legisladores_diputados",
        ["distrito"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legisladores_diputados_id"),
        "legisladores_diputados",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legisladores_diputados_nombre"),
        "legisladores_diputados",
        ["nombre"],
        unique=False,
    )
    op.create_table(
        "legisladores_senadores",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("distrito", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sexo", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("imagen", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("senador_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_legisladores_senadores_distrito"),
        "legisladores_senadores",
        ["distrito"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legisladores_senadores_id"),
        "legisladores_senadores",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legisladores_senadores_nombre"),
        "legisladores_senadores",
        ["nombre"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legisladores_senadores_senador_id"),
        "legisladores_senadores",
        ["senador_id"],
        unique=True,
    )
    op.create_table(
        "votaciones_diputados",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("asunto_id", sa.Integer(), nullable=False),
        sa.Column("bloque_id", sa.Integer(), nullable=False),
        sa.Column("voto", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("diputado_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_votaciones_diputados_asunto_id"),
        "votaciones_diputados",
        ["asunto_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_votaciones_diputados_bloque_id"),
        "votaciones_diputados",
        ["bloque_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_votaciones_diputados_diputado_id"),
        "votaciones_diputados",
        ["diputado_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_votaciones_diputados_id"), "votaciones_diputados", ["id"], unique=False
    )
    op.create_table(
        "votaciones_senadores",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("asunto_id", sa.Integer(), nullable=False),
        sa.Column("bloque_id", sa.Integer(), nullable=False),
        sa.Column("voto", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("senador_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_votaciones_senadores_asunto_id"),
        "votaciones_senadores",
        ["asunto_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_votaciones_senadores_bloque_id"),
        "votaciones_senadores",
        ["bloque_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_votaciones_senadores_id"), "votaciones_senadores", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_votaciones_senadores_senador_id"),
        "votaciones_senadores",
        ["senador_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_votaciones_senadores_senador_id"), table_name="votaciones_senadores"
    )
    op.drop_index(op.f("ix_votaciones_senadores_id"), table_name="votaciones_senadores")
    op.drop_index(
        op.f("ix_votaciones_senadores_bloque_id"), table_name="votaciones_senadores"
    )
    op.drop_index(
        op.f("ix_votaciones_senadores_asunto_id"), table_name="votaciones_senadores"
    )
    op.drop_table("votaciones_senadores")
    op.drop_index(op.f("ix_votaciones_diputados_id"), table_name="votaciones_diputados")
    op.drop_index(
        op.f("ix_votaciones_diputados_diputado_id"), table_name="votaciones_diputados"
    )
    op.drop_index(
        op.f("ix_votaciones_diputados_bloque_id"), table_name="votaciones_diputados"
    )
    op.drop_index(
        op.f("ix_votaciones_diputados_asunto_id"), table_name="votaciones_diputados"
    )
    op.drop_table("votaciones_diputados")
    op.drop_index(
        op.f("ix_legisladores_senadores_senador_id"),
        table_name="legisladores_senadores",
    )
    op.drop_index(
        op.f("ix_legisladores_senadores_nombre"), table_name="legisladores_senadores"
    )
    op.drop_index(
        op.f("ix_legisladores_senadores_id"), table_name="legisladores_senadores"
    )
    op.drop_index(
        op.f("ix_legisladores_senadores_distrito"), table_name="legisladores_senadores"
    )
    op.drop_table("legisladores_senadores")
    op.drop_index(
        op.f("ix_legisladores_diputados_nombre"), table_name="legisladores_diputados"
    )
    op.drop_index(
        op.f("ix_legisladores_diputados_id"), table_name="legisladores_diputados"
    )
    op.drop_index(
        op.f("ix_legisladores_diputados_distrito"), table_name="legisladores_diputados"
    )
    op.drop_index(
        op.f("ix_legisladores_diputados_diputado_id"),
        table_name="legisladores_diputados",
    )
    op.drop_table("legisladores_diputados")
    op.drop_index(op.f("ix_bloques_senadores_id"), table_name="bloques_senadores")
    op.drop_index(
        op.f("ix_bloques_senadores_bloque_id"), table_name="bloques_senadores"
    )
    op.drop_table("bloques_senadores")
    op.drop_index(op.f("ix_bloques_diputados_id"), table_name="bloques_diputados")
    op.drop_index(
        op.f("ix_bloques_diputados_bloque_id"), table_name="bloques_diputados"
    )
    op.drop_table("bloques_diputados")
    op.drop_index(op.f("ix_asuntos_senadores_id"), table_name="asuntos_senadores")
    op.drop_index(
        op.f("ix_asuntos_senadores_asunto_id"), table_name="asuntos_senadores"
    )
    op.drop_table("asuntos_senadores")
    op.drop_index(op.f("ix_asuntos_diputados_id"), table_name="asuntos_diputados")
    op.drop_index(
        op.f("ix_asuntos_diputados_asunto_id"), table_name="asuntos_diputados"
    )
    op.drop_table("asuntos_diputados")
    # ### end Alembic commands ###
